server {
  listen 80;
  server_name registry.mydomain.com;

  location ~/.well-known/acme-challenge/ {
    root /usr/share/nginx/html;
    allow all;
  }

  location / {
    root /usr/share/nginx/html/;
    index  index.html;
  }
}
