map "$http_x_app_id:$http_x_app_secret" $allowed_app {
  default 0;

  # Format: "App-ID:App-Secret" "1" (meaning authorized)
  "29412b0478e4:Mjk0MTJiMDQ3OGU0" 1;
  "good:badd" 1;
}

upstream gotenberg_backend {
  server common_gotenberg:3000;
  keepalive 32;
}

server {
  listen 80;
  server_name gotenberg.localhost.com; # Replace with your domain or server IP

  if ($allowed_app = 0) {
    return 401 '{"error": "Unauthorized: Invalid Application."}';
  }

  add_header Content-Type application/json;

  # Redirect HTTP to HTTPS (uncomment if using SSL/TLS)
  # return 301 https://$host$request_uri;

  # Increase body size limit for large HTML payloads or multipart uploads (e.g., merging or office files)
  client_max_body_size 100M;

  # Extended timeouts for heavy PDF/Office document rendering
  proxy_connect_timeout 300s;
  proxy_send_timeout    300s;
  proxy_read_timeout    300s;

  location / {
    proxy_pass http://gotenberg_backend; # Points to the local port exposed by Docker

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Disable buffering to stream generated files immediately if needed
    proxy_buffering off;
    proxy_cache off;
  }
}
