[global_config]
  handle_size = 7
  inactive_color_offset = 0.6944444444444444
  inactive_bg_color_offset = 0.16666666666666666
[keybindings]
  go_up = <Alt>k
  go_down = <Alt>j
  go_left = <Alt>h
  go_right = <Alt>l
  next_tab = <Primary>h
  layout_launcher = <Primary>KP_0
[profiles]
  [[default]]
    background_color = "#282828"
    font = JetBrainsMono Nerd Font Medium 9
    foreground_color = "#ebdbb2"
    palette = "#282828:#cc241d:#98971a:#d79921:#458588:#b16286:#689d6a:#a89984:#928374:#fb4934:#b8bb26:#fabd2f:#83a598:#d3869b:#8ec07c:#ebdbb2"
    use_system_font = False
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
