x-default-opts: &default-opts
  logging:
    options:
      max-size: "100m"

networks:
  postgres:
    driver: overlay
  backend:
    driver: overlay

services:
  pgadmin:
    image: dpage/pgadmin4:snapshot
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ${PGADMIN_DATA}:/var/lib/pgadmin
    networks:
      - backend
      - postgres
